In [ ]:
from twolenspy.HDPE_lens import HDEP_2lens
import h5py as h5
import numpy as np
import matplotlib.pyplot as plt


In [ ]:
PO_sampling_file = 'twolenspy/HDPE_PO_points.h5'


## Using uniform sampling to study the polarizaiton rotation at 45deg

In [ ]:
dx_list = [20,40,60,80,100,120]
angle_list = [0,15,30,45,60,75,90,105,120,135,150,165]
freq_list = [120,150]
for freq in freq_list:
    factor = 1.0
    if freq < 90:
        freq_check = 90
    elif freq < 120:
        freq_check = 120
    elif freq < 150:
        freq_check = 150
    elif freq >150:
        freq_check = 150
        factor = 2
    for angle in angle_list:
        for item in dx_list:
            print(freq, angle,item)
            with h5.File(PO_sampling_file,'r') as f:
                PO_no = f[str(freq_check)+'GHz'][str(item)][str(45)]['POpoints'][:]

            Model1 = HDEP_2lens(freq,
                        feedpos = [item,0,0],
                        feedrot = [0,0,angle],
                        AR_file = 'AR_LIB/HDPE_ARC.h5',
                        groupname= str(freq)+'GHz',
                        outputfolder = '../Data/HDPE/AR/'+str(freq)+'GHz/',
                        grid_sizex = 0.2,
                        grid_sizey = 0.2)
            
            Model1.run_po(PO_no[0:2],
                          PO_no[2:4],
                        sampling_type = 'less')
# 120GHz, 0mm, 135 missing


In [ ]:
dx_list = [40,60,80,100,120] #[0,20,]
angle_list = [45]#[0,15,30,45,60,75,90,105,120,135,150,165]
freq_list = [155,160,165,170]
for freq in freq_list:
    for angle in angle_list:
        for item in dx_list:
            print(freq, angle,item)
            freq_check = 150
            with h5.File(PO_sampling_file,'r') as f:
                PO_no = f[str(freq_check)+'GHz'][str(item)][str(angle)]['POpoints'][:]

            Model1 = HDEP_2lens(freq,
                        feedpos = [item,0,0],
                        feedrot = [0,0,angle],
                        AR_file = 'AR_LIB/HDPE_ARC.h5',
                        groupname= str(freq)+'GHz',
                        outputfolder = '../Data/HDPE/AR/'+str(freq)+'GHz/')
            factor = 2            
            PO_No = np.array(PO_no,dtype = np.int32)*factor
            PO_No = PO_No.tolist()
            Model1.run_po(PO_No[0:2],
                          PO_No[2:4],
                        sampling_type = 'less')


In [ ]:
dx_list = [0,20]#[40,60,80,100,120] #
angle_list = [45]#[0,15,30,45,60,75,90,105,120,135,150,165]
freq_list = [160,165,170]#[155,160,165,170]
for freq in freq_list:
    for angle in angle_list:
        for item in dx_list:
            print(freq, angle,item)
            freq_check = 150
            with h5.File(PO_sampling_file,'r') as f:
                PO_no = f[str(freq_check)+'GHz'][str(item)][str(angle)]['POpoints'][:]

            Model1 = HDEP_2lens(freq,
                        feedpos = [item,0,0],
                        feedrot = [0,0,angle],
                        AR_file = 'AR_LIB/HDPE_ARC.h5',
                        groupname= str(freq)+'GHz',
                        outputfolder = '../Data/HDPE/AR/'+str(freq)+'GHz/')
            factor = 2            
            PO_No = np.array(PO_no,dtype = np.int32)*factor
            PO_No = PO_No.tolist()
            Model1.run_po(PO_No[0:2],
                          PO_No[2:4],
                        sampling_type = 'less')



150GHz: Lens3 2.5 2.5, lens2 3.5,2.5, lens1 3.5 2.5

In [ ]:
dx_list = [20,40,60,80,100,120] 
angle_list = [0,90]#[0,15,30,45,60,75,90,105,120,135,150,165]
freq_list = [155,160,165,170]
for freq in freq_list:
    for angle in angle_list:
        for item in dx_list:
            print(freq, angle,item)
            freq_check = 150
            with h5.File(PO_sampling_file,'r') as f:
                PO_no = f[str(freq_check)+'GHz'][str(item)][str(angle)]['POpoints'][:]

            Model1 = HDEP_2lens(freq,
                        feedpos = [item,0,0],
                        feedrot = [0,0,angle],
                        AR_file = 'AR_LIB/HDPE_ARC.h5',
                        groupname= str(freq)+'GHz',
                        outputfolder = '../Data/HDPE/AR/'+str(freq)+'GHz/')
            factor = 2            
            PO_No = np.array(PO_no,dtype = np.int32)*factor
            PO_No = PO_No.tolist()
            Model1.run_po(PO_No[0:2],
                          PO_No[2:4],
                        sampling_type = 'less')


In [4]:
dx_list = [0] 
angle_list = [135]#[0,15,30,45,60,75,90,105,120,135,150,165]
freq_list = [90,120,150]#[155,160,165,170]
for freq in freq_list:
    for angle in angle_list:
        for item in dx_list:
            print(freq, angle,item)
            freq_check = freq
            with h5.File(PO_sampling_file,'r') as f:
                PO_no = f[str(freq_check)+'GHz'][str(item)][str(45)]['POpoints'][:]

            Model1 = HDEP_2lens(freq,
                        feedpos = [item,0,0],
                        feedrot = [0,0,angle],
                        AR_file = 'AR_LIB/HDPE_ARC.h5',
                        groupname= str(freq)+'GHz',
                        outputfolder = '../Data/HDPE/AR/'+str(freq)+'GHz/')
            factor = 1          
            PO_No = np.array(PO_no,dtype = np.int32)*factor
            PO_No = PO_No.tolist()
            Model1.run_po(PO_No[0:2],
                          PO_No[2:4],
                        sampling_type = 'less')


90 135 0
sampling type : less
sampling type : less
Gain of the Guassian feedhonr!
-5.274703200714645 dB
Batch size: 253


100%|██████████| 45/45 [00:00<00:00, 2463.63it/s]
/home/xren/Documents/Lens_PO/PO_test/Kirchhoffpy/FresnelCoeff.py:240: ComplexWarning: Casting complex values to real discards the imaginary part
  r_p[NN_t] = 1.0 * np.exp(1j*np.pi)
/home/xren/Documents/Lens_PO/PO_test/Kirchhoffpy/FresnelCoeff.py:241: ComplexWarning: Casting complex values to real discards the imaginary part
  r_s[NN_t] = 1.0 * np.exp(1j*np.pi)


Transform f1
poynting value max!
0.0005231092981681856
12.760281863791008
f2
poynting value max!
0.0003633455507100834
12.264634430638965
f2 transmission
poynting value max!
12.210014570607719
sampling type : less
sampling type : less
../Data/HDPE/AR/90GHz/L2_po_cur_0_0_0mm_polar_135deg.h5
Here
Batch size: 1530


100%|██████████| 29/29 [00:00<00:00, 6258.22it/s]


Batch size: 387


100%|██████████| 103/103 [00:01<00:00, 55.91it/s]


Transform f1
poynting value max!
4.171586535396372e-05
6.847292600854186
f2
poynting value max!
4.5661724707153455e-05
6.628779923200628
f2 transmission
poynting value max!
6.747623211299302
../Data/HDPE/AR/90GHz/L1_po_cur_0_0_0mm_polar_135deg.h5
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
*(**)
Batch size: 1459


100%|██████████| 27/27 [00:00<00:00, 5914.57it/s]


120 135 0
sampling type : less
sampling type : less
Gain of the Guassian feedhonr!
-7.773477846357553 dB
Batch size: 191


100%|██████████| 101/101 [00:01<00:00, 57.30it/s]


Transform f1
poynting value max!
0.00029614970160216
12.860831535888686
f2
poynting value max!
0.00020515483640975128
12.360447901591382
f2 transmission
poynting value max!
12.385912248059393
sampling type : less
sampling type : less
../Data/HDPE/AR/120GHz/L2_po_cur_0_0_0mm_polar_135deg.h5
Here
Batch size: 899


100%|██████████| 85/85 [00:01<00:00, 67.35it/s]


Batch size: 226


100%|██████████| 314/314 [00:08<00:00, 37.66it/s]


Transform f1
poynting value max!
2.423623725239955e-05
6.988575778566329
f2
poynting value max!
2.7179114160645918e-05
6.767148472484606
f2 transmission
poynting value max!
6.937739789062086
../Data/HDPE/AR/120GHz/L1_po_cur_0_0_0mm_polar_135deg.h5
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
*(**)
Batch size: 819


100%|██████████| 49/49 [00:00<00:00, 130.82it/s]


150 135 0
sampling type : less
sampling type : less
Gain of the Guassian feedhonr!
-9.711678082057606 dB
Batch size: 124


100%|██████████| 241/241 [00:06<00:00, 39.03it/s]


Transform f1
poynting value max!
0.00018820136224542233
12.802683637253883
f2
poynting value max!
0.00013148013278210972
12.303373914421423
f2 transmission
poynting value max!
12.243928371083172
sampling type : less
sampling type : less
../Data/HDPE/AR/150GHz/L2_po_cur_0_0_0mm_polar_135deg.h5
Here
Batch size: 584


100%|██████████| 205/205 [00:05<00:00, 40.99it/s]


Batch size: 145


100%|██████████| 740/740 [00:21<00:00, 34.18it/s]


Transform f1
poynting value max!
1.508426985129749e-05
6.853602008550696
f2
poynting value max!
1.5789202194036312e-05
6.636753071299137
f2 transmission
poynting value max!
6.765954019405857
../Data/HDPE/AR/150GHz/L1_po_cur_0_0_0mm_polar_135deg.h5
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
*(**)
Batch size: 542


100%|██████████| 74/74 [00:01<00:00, 49.05it/s]
