In [1]:
from SOSATpopy import sosat


10


In [2]:
freq_list= [92,94,96,98,100,102] #[78,80,82,84,86,88,90,


In [ ]:
dx_list = [180]#,[160,100,60,20]# 
angle_list = [45]#[45,30,15,0,-15,-30,-45] 
for freq in freq_list:
    for angle in angle_list:
        for item in dx_list:
            print(freq, angle,item)
            Model1 = sosat(freq,
                        feedpos = [item,0,0],
                        feedrot = [0,0,angle],
                        AR_file = 'AR_LIB/Ideal_AR.h5',
                        groupname= 'ideal_AR',#str(freq)+'GHz',
                        outputfolder = '../Data/output_polar_ideal_AR/'+str(freq)+'GHz/')
            factor1 = 3
            factor2 = 2
            '''
            if freq >90:
                factor1 = 2.5
                factor2 = 1.5
            '''
            Model1.run_po([[int(380*factor1),int(1880*factor2)],[int(240*factor1),int(2160*factor2)]],
                        [[int(370*factor1),int(2320*factor2)],[int(195*factor1),int(390*factor2)]],
                        [[int(340*factor1),int(2320*factor2)],[int(300*factor1),int(200*factor2)]],)



In [ ]:
dx_list = [160,100,60,20,0]# [180]#,
angle_list = [45]#[45,30,15,0,-15,-30,-45] 
for freq in freq_list:
    for angle in angle_list:
        for item in dx_list:
            print(freq, angle,item)
            Model1 = sosat(freq,
                        feedpos = [item,0,0],
                        feedrot = [0,0,angle],
                        AR_file = 'AR_LIB/normal_groove_AR.h5',
                        groupname= str(freq)+'GHz',
                        outputfolder = '../Data/output_polar_normal_groove_AR/'+str(freq)+'GHz/')
            factor1 = 2
            factor2 = 1
            if freq >90:
                factor1 = 2.5
                factor2 = 1.5
            Model1.run_po([[int(380*factor1),int(1880*factor2)],[int(240*factor1),int(2160*factor2)]],
                        [[int(370*factor1),int(2320*factor2)],[int(195*factor1),int(390*factor2)]],
                        [[int(340*factor1),int(2320*factor2)],[int(300*factor1),int(200*factor2)]],)



92 45 160
26584903304305.848
Gain of the Guassian feedhonr!
-2.3863886873293603 dB
Batch size: 10


100%|██████████| 123997/123997 [1:03:41<00:00, 32.44it/s]
/home/xren/Documents/Lens_PO/PO_test/Kirchhoffpy/LensPO.py:348: ComplexWarning: Casting complex values to real discards the imaginary part
  r_p[NN_t] = 1.0 * np.exp(1j*np.pi)
/home/xren/Documents/Lens_PO/PO_test/Kirchhoffpy/LensPO.py:349: ComplexWarning: Casting complex values to real discards the imaginary part
  r_s[NN_t] = 1.0 * np.exp(1j*np.pi)


../Data/output_polar_normal_groove_AR/92GHz/L3_po_cur_160_0_0mm_polar_45deg.h5
Here
Batch size: 13


100%|██████████| 157912/157912 [1:16:58<00:00, 34.19it/s]


Batch size: 8


100%|██████████| 22897/22897 [12:02<00:00, 31.71it/s]


../Data/output_polar_normal_groove_AR/92GHz/L2_po_cur_160_0_0mm_polar_45deg.h5
Here
Batch size: 94


100%|██████████| 20068/20068 [10:12<00:00, 32.75it/s]


Batch size: 9


100%|██████████| 16221/16221 [08:48<00:00, 30.70it/s]


../Data/output_polar_normal_groove_AR/92GHz/L1_po_cur_160_0_0mm_polar_45deg.h5
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
*(**)
Batch size: 394


100%|██████████| 637/637 [00:26<00:00, 24.00it/s]


92 45 100
26584903304305.848
Gain of the Guassian feedhonr!
-2.385743698179258 dB
Batch size: 10


100%|██████████| 123997/123997 [1:08:06<00:00, 30.34it/s]


../Data/output_polar_normal_groove_AR/92GHz/L3_po_cur_100_0_0mm_polar_45deg.h5
Here
Batch size: 13


100%|██████████| 157912/157912 [1:21:42<00:00, 32.21it/s]


Batch size: 8


100%|██████████| 22897/22897 [12:04<00:00, 31.61it/s]


../Data/output_polar_normal_groove_AR/92GHz/L2_po_cur_100_0_0mm_polar_45deg.h5
Here
Batch size: 94


100%|██████████| 20068/20068 [10:12<00:00, 32.75it/s]


Batch size: 9


100%|██████████| 16221/16221 [08:47<00:00, 30.74it/s]


../Data/output_polar_normal_groove_AR/92GHz/L1_po_cur_100_0_0mm_polar_45deg.h5
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
*(**)
Batch size: 394


100%|██████████| 637/637 [00:26<00:00, 23.90it/s]


92 45 60
26584903304305.848
Gain of the Guassian feedhonr!
-2.3863812106448554 dB
Batch size: 10


100%|██████████| 123997/123997 [1:08:08<00:00, 30.33it/s]


../Data/output_polar_normal_groove_AR/92GHz/L3_po_cur_60_0_0mm_polar_45deg.h5
Here
Batch size: 13


100%|██████████| 157912/157912 [1:21:44<00:00, 32.19it/s]


Batch size: 8


100%|██████████| 22897/22897 [12:02<00:00, 31.71it/s]


../Data/output_polar_normal_groove_AR/92GHz/L2_po_cur_60_0_0mm_polar_45deg.h5
Here
Batch size: 94


100%|██████████| 20068/20068 [10:08<00:00, 33.00it/s]


Batch size: 9


100%|██████████| 16221/16221 [08:50<00:00, 30.56it/s]


../Data/output_polar_normal_groove_AR/92GHz/L1_po_cur_60_0_0mm_polar_45deg.h5
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
*(**)
Batch size: 394


100%|██████████| 637/637 [00:26<00:00, 23.63it/s]


92 45 20
26584903304305.848
Gain of the Guassian feedhonr!
-2.385773299660329 dB
Batch size: 10


100%|██████████| 123997/123997 [1:07:11<00:00, 30.75it/s]


In [ ]:
dx_list = [180,160,100,60,20]
angle_list = [45]#[45,30,15,0,-15,-30,-45] 
for freq in freq_list:
    for angle in angle_list:
        for item in dx_list:
            print(freq, angle,item)
            Model1 = sosat(freq,
                        feedpos = [item,0,0],
                        feedrot = [0,0,angle],
                        AR_file = 'AR_LIB/leaning_groove_AR.h5',
                        groupname= str(freq)+'GHz',
                        outputfolder = '../Data/output_polar_leaning_groove_AR/'+str(freq)+'GHz/')
            factor1 = 2
            factor2 = 1
            if freq >90:
                factor1 = 2.5
                factor2 = 1.5
            Model1.run_po([[int(380*factor1),int(1880*factor2)],[int(240*factor1),int(2160*factor2)]],
                        [[int(370*factor1),int(2320*factor2)],[int(195*factor1),int(390*factor2)]],
                        [[int(340*factor1),int(2320*factor2)],[int(300*factor1),int(200*factor2)]],)


